Repository ClearTK/cleartk, pull requests merged in 2022-11, with the labels that each got.

#449 #448 Update dependencies
  cleartk-ml-tksvmlight/src/main/java/org/cleartk/ml/tksvmlight/TkSvmLightBooleanOutcomeClassifierBuilder.java
  cleartk-ml-tksvmlight/src/test/java/org/cleartk/ml/tksvmlight/RunTkSvmLightTest.java
  cleartk-ml/pom.xml
  cleartk-ml/src/test/java/org/cleartk/ml/jar/JarDataWriterTest.java
  cleartk-ml/src/test/java/org/cleartk/ml/viterbi/ViterbiDataWriterTest.java
  cleartk-timeml/pom.xml
  cleartk-timeml/src/test/java/org/cleartk/timeml/TimeMlAnnotateTest.java
  pom.xml
Labels: Refactoring

#445 [SECURITY] Fix Temporary Directory Hijacking or Information Disclosure Vulnerability
  cleartk-timeml/src/main/java/org/cleartk/timeml/tlink/VerbClauseTemporalTrain.java
Labels: bug

#443 #442 - Upgrade to UIMAv3
  cleartk-corpus/src/main/java/org/cleartk/corpus/conll2005/Conll2005GoldAnnotator.java
  cleartk-corpus/src/main/java/org/cleartk/corpus/timeml/TempEval2013Writer.java
  cleartk-ml-crfsuite/pom.xml
  cleartk-ml-crfsuite/src/main/java/org/cleartk/ml/crfsuite/CrfSuiteWrapper.java
  cleartk-ml-liblinear/src/test/java/org/cleartk/ml/liblinear/LibLinearTest.java
  cleartk-ml-tksvmlight/src/main/java/org/cleartk/ml/tksvmlight/kernel/TreeKernel_ImplBase.java
  cleartk-ml-weka/src/main/java/org/cleartk/ml/weka/WekaStringOutcomeClassifier.java
  cleartk-ml/pom.xml
  cleartk-ml/src/test/java/org/cleartk/ml/jar/JarDataWriterTest.java
  cleartk-ml/src/test/java/org/cleartk/ml/viterbi/ViterbiDataWriterTest.java
  cleartk-opennlp-tools/src/main/java/org/cleartk/opennlp/tools/PosTagger.java
  cleartk-opennlp-tools/src/main/java/org/cleartk/opennlp/tools/Tokenizer.java
  cleartk-opennlp-tools/src/main/java/org/cleartk/opennlp/tools/parser/DefaultOutputTypesHelper.java
  cleartk-stanford-corenlp/src/test/java/org/cleartk/stanford/corenlp/StanfordCoreNlpTest.java
  cleartk-test-util/src/main/java/org/cleartk/test/util/TypeTestUtil.java
  cleartk-timeml/pom.xml
  cleartk-timeml/src/test/java/org/cleartk/timeml/TimeMlAnnotateTest.java
  cleartk-util/src/main/java/org/cleartk/util/PlatformDetection.java
  pom.xml
Labels: Refactoring

#450 #448 - Update dependencies
  cleartk-stanford-corenlp/pom.xml
  cleartk-stanford-corenlp/src/main/java/org/cleartk/stanford/corenlp/StanfordCoreNlpAnnotator.java
  cleartk-stanford-corenlp/src/test/java/org/cleartk/stanford/corenlp/StanfordCoreNlpTest.java
  pom.xml
Labels: Refactoring

#451 #448 - Update dependencies
  cleartk-corpus/pom.xml
  cleartk-corpus/src/main/java/org/cleartk/corpus/timeml/TempEval2013Writer.java
  cleartk-eval/pom.xml
  cleartk-eval/src/main/java/org/cleartk/eval/AnnotationStatistics.java
  cleartk-eval/src/main/java/org/cleartk/eval/util/ConfusionMatrix.java
  cleartk-maltparser/pom.xml
  cleartk-ml-liblinear/src/test/java/org/cleartk/ml/liblinear/LibLinearTest.java
  cleartk-ml-tksvmlight/src/main/java/org/cleartk/ml/tksvmlight/kernel/TreeKernel_ImplBase.java
  cleartk-ml-weka/src/main/java/org/cleartk/ml/weka/WekaStringOutcomeClassifier.java
  cleartk-ml/pom.xml
  cleartk-ml/src/main/java/org/cleartk/ml/viterbi/ViterbiClassifier.java
  cleartk-timeml/src/main/java/org/cleartk/timeml/eval/Model.java
  cleartk-util/pom.xml
  cleartk-util/src/main/java/org/cleartk/util/PlatformDetection.java
  pom.xml
Labels: Refactoring

#452 Issue #442: Upgrade to UIMAv3
  pom.xml
Labels: ⚙️ Refactoring

#454 Issue #453: Add Maven dependency checking plugin
  cleartk-berkeleyparser/pom.xml
  cleartk-clearnlp/pom.xml
  cleartk-corpus/pom.xml
  cleartk-eval/pom.xml
  cleartk-examples/pom.xml
  cleartk-feature/pom.xml
  cleartk-maltparser/pom.xml
  cleartk-ml-crfsuite/pom.xml
  cleartk-ml-crfsuite/src/test/java/org/cleartk/ml/crfsuite/CrfSuiteClassifierTest.java
  cleartk-ml-liblinear/pom.xml
  cleartk-ml-libsvm-tk/pom.xml
  cleartk-ml-libsvm/pom.xml
  cleartk-ml-mallet/pom.xml
  cleartk-ml-opennlp-maxent/pom.xml
  cleartk-ml-script/pom.xml
  cleartk-ml-svmlight/pom.xml
  cleartk-ml-tksvmlight/pom.xml
  cleartk-ml-weka/pom.xml
  cleartk-ml/pom.xml
  cleartk-opennlp-tools/pom.xml
  cleartk-snowball/pom.xml
  cleartk-stanford-corenlp/pom.xml
  cleartk-summarization/pom.xml
  cleartk-timeml/pom.xml
  cleartk-token/pom.xml
  cleartk-type-system/pom.xml
  cleartk-util/pom.xml
  cleartk-util/src/main/java/org/cleartk/util/PlatformDetection.java
  pom.xml
Labels: ⚙️ Refactoring

#455 #448 - Update dependencies
  cleartk-ml-mallet/pom.xml
  pom.xml
Labels: ⚙️ Refactoring

#456 #448 - Update dependencies
  cleartk-ml-opennlp-maxent/pom.xml
  cleartk-ml-opennlp-maxent/src/main/java/org/cleartk/ml/opennlp/maxent/MaxentBooleanOutcomeClassifier.java
  cleartk-ml-opennlp-maxent/src/main/java/org/cleartk/ml/opennlp/maxent/MaxentBooleanOutcomeDataWriter.java
  cleartk-ml-opennlp-maxent/src/main/java/org/cleartk/ml/opennlp/maxent/MaxentClassifierBuilder_ImplBase.java
  cleartk-ml-opennlp-maxent/src/main/java/org/cleartk/ml/opennlp/maxent/MaxentClassifier_ImplBase.java
  cleartk-ml-opennlp-maxent/src/main/java/org/cleartk/ml/opennlp/maxent/MaxentDataWriter_ImplBase.java
  cleartk-ml-opennlp-maxent/src/main/java/org/cleartk/ml/opennlp/maxent/MaxentStringOutcomeClassifier.java
  cleartk-ml-opennlp-maxent/src/main/java/org/cleartk/ml/opennlp/maxent/MaxentStringOutcomeDataWriter.java
  cleartk-ml-opennlp-maxent/src/test/java/org/cleartk/ml/opennlp/maxent/MaxentStringOutcomeClassifierTest.java
  cleartk-ml/src/main/java/org/cleartk/ml/jar/JarClassifierBuilder.java
  cleartk-opennlp-tools/pom.xml
  cleartk-timeml/pom.xml
  pom.xml
Labels: ⚙️ Refactoring

#458 Issue #457: Update dependencies
  pom.xml
Labels: ⚙️ Refactoring

#459 #448 - Update dependencies
  cleartk-corpus/pom.xml
  cleartk-examples/pom.xml
  cleartk-ml-crfsuite/src/test/java/org/cleartk/ml/crfsuite/CrfSuiteClassifierTest.java
  cleartk-util/src/main/java/org/cleartk/util/PlatformDetection.java
  pom.xml
Labels: ⚙️ Refactoring

#461 Issue #460: Introduce a BOM
  cleartk-berkeleyparser/pom.xml
  cleartk-bom/pom.xml
  cleartk-clearnlp/pom.xml
  cleartk-corpus/pom.xml
  cleartk-eval/pom.xml
  cleartk-examples/pom.xml
  cleartk-feature/pom.xml
  cleartk-maltparser/pom.xml
  cleartk-ml-crfsuite/pom.xml
  cleartk-ml-liblinear/pom.xml
  cleartk-ml-libsvm-tk/pom.xml
  cleartk-ml-libsvm/pom.xml
  cleartk-ml-mallet/pom.xml
  cleartk-ml-opennlp-maxent/pom.xml
  cleartk-ml-script/pom.xml
  cleartk-ml-svmlight/pom.xml
  cleartk-ml-tksvmlight/pom.xml
  cleartk-ml-weka/pom.xml
  cleartk-ml/pom.xml
  cleartk-opennlp-tools/pom.xml
  cleartk-snowball/pom.xml
  cleartk-stanford-corenlp/pom.xml
  cleartk-summarization/pom.xml
  cleartk-test-util/pom.xml
  cleartk-timeml/pom.xml
  cleartk-token/pom.xml
  cleartk-type-system/pom.xml
  cleartk-util/pom.xml
  pom.xml
Labels: ⭐️ Enhancement

#464 Issue #463: Ability to work in multi-classloader environments
  cleartk-ml-mallet/src/main/java/org/cleartk/ml/mallet/MalletClassifierBuilder_ImplBase.java
  cleartk-ml/src/main/java/org/cleartk/ml/jar/EncodingJarClassifierBuilder.java
  cleartk-ml/src/main/java/org/cleartk/ml/jar/GenericDataWriterFactory.java
  cleartk-ml/src/main/java/org/cleartk/ml/jar/JarClassifierBuilder.java
  cleartk-test-util/src/main/java/org/cleartk/test/util/ParametersTestUtil.java
  cleartk-util/pom.xml
  cleartk-util/src/main/java/org/cleartk/util/ClassLookup.java
  cleartk-util/src/main/java/org/cleartk/util/ae/linewriter/LineWriter.java
Labels: ⭐️ Enhancement

#466 Issue #465: Remove use of deprecated OSS Sonatype parent POM
  .gitignore
  cleartk-clearnlp/src/main/java/org/cleartk/clearnlp/Tokenizer_ImplBase.java
  cleartk-corpus/src/main/java/org/cleartk/corpus/penntreebank/PennTreebankReader.java
  cleartk-corpus/src/main/java/org/cleartk/corpus/propbank/PropbankGoldReader.java
  cleartk-corpus/src/main/java/org/cleartk/corpus/propbank/util/Propbank.java
  cleartk-corpus/src/main/java/org/cleartk/corpus/propbank/util/PropbankRelation.java
  cleartk-corpus/src/main/java/org/cleartk/corpus/propbank/util/Proplabel.java
  cleartk-eval/src/main/java/org/cleartk/eval/Evaluation_ImplBase.java
  cleartk-feature/src/main/java/org/cleartk/feature/syntax/SyntacticPathExtractor.java
  cleartk-ml-mallet/src/main/java/org/cleartk/ml/mallet/grmm/GrmmClassifierBuilder.java
  cleartk-ml-opennlp-maxent/src/main/java/org/cleartk/ml/opennlp/maxent/MaxentDataWriter_ImplBase.java
  cleartk-ml/src/main/java/org/cleartk/ml/feature/extractor/CombinedExtractor1.java
  cleartk-ml/src/main/java/org/cleartk/ml/feature/transform/TrainableExtractor.java
  cleartk-ml/src/main/java/org/cleartk/ml/util/PublicFieldDataWriter.java
  cleartk-ml/src/main/java/org/cleartk/ml/util/PublicFieldSequenceDataWriter.java
  cleartk-ml/src/main/java/org/cleartk/ml/viterbi/ViterbiClassifier.java
  cleartk-test-util/src/main/java/org/cleartk/test/util/CleartkTestBase.java
  cleartk-test-util/src/main/java/org/cleartk/test/util/DefaultTestBase.java
  cleartk-token/src/main/java/org/cleartk/token/tokenizer/Tokenizer_ImplBase.java
  cleartk-util/src/main/java/org/cleartk/util/cr/RegexFileFilter.java
  pom.xml
Labels: ⚙️ Refactoring
